name: Test Raft
on:
  push:
    branches:
      - ci
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19
      - name: Install Go JUnit Report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
      - name: Run Test
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          cd ${{ github.workspace }}/src/raft/        && go test -v | go-junit-report -set-exit-code -iocopy -out raft_report.xml
          cd ${{ github.workspace }}//kvraft/      && go test -v | go-junit-report -set-exit-code -iocopy -out kvraft_report.xml
          cd ${{ github.workspace }}/src/shardctrler/ && go test -v | go-junit-report -set-exit-code -iocopy -out shardctrler_report.xml
          export shardkv_output="${{ github.workspace }}/shardkv.log"
          cd ${{ github.workspace }}/src/shardkv/     && go test -v | go-junit-report -set-exit-code -iocopy -out shardkv_report.xml
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            ${{ github.workspace }}/src/raft/raft_report.xml
            ${{ github.workspace }}/src/kvraft/kvraft_report.xml
            ${{ github.workspace }}/src/shardctrler/shardctrler_report.xml
            ${{ github.workspace }}/src/shardkv/shardkv_report.xml
        if: always()
      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: ShardKV Log
          path: ${{ github.workspace }}/shardkv.log