jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Install Go JUnit Report
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
      - name: Run Test
        run: |
          export GOPATH="$HOME/go/"
          export PATH=$PATH:$GOPATH/bin
          cd src/raft/        && go test -v | go-junit-report -set-exit-code -iocopy -out raft_report.xml
          cd src/kvraft/      && go test -v | go-junit-report -set-exit-code -iocopy -out kvraft_report.xml
          cd src/shardctrler/ && go test -v | go-junit-report -set-exit-code -iocopy -out shardctrler_report.xml
          cd src/shardkv/     && go test -v | go-junit-report -set-exit-code -iocopy -out shardkv_report.xml
      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            raft_report.xml
            kvraft_report.xml
            shardctrler_report.xml
            shardkv_report.xml
        if: always()